name: Push kernel
on:
  push:
    branches:
      - 'solution/*'
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Checkout
        uses: actions/checkout@v2
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install dependencies
        run: |
          echo "::group::Requirements"
          pip install -r requirements.txt
          echo "::endgroup::"

      - name: Init metadata and code file
        run: python kci/init.py -s "$(git branch --show-current)" -r "$(git rev-parse --short HEAD)"
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}

      - name: Push kernel
        run: kaggle k push
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
